### ISSUE TITLE
Mailer adapter does not behave as expected

### ISSUE THREAD

**Issue by mquan** [palkan/isolator#26]
There seem to be two problems, but I'm unsure if they're related. Please let me know if you'd like to split the problems into two separate issues. Here's the setup:

```
class User
  after_create :send_first_email
  after_commit :send_second_email, on: :create

  private

  def send_first_email
    UserMailer.delay.first_email(id)
  end

  def send_second_email
    UserMailer.second_email(id).deliver_later
  end
end
```

When I run a simple create spec, I get `Isolator::BackgroundJobError` but it's because of `send_second_email`.

1. I believe the first problem is the mailer adapter doesn't recognize `UserMailer.delay.first_email(id)` as a job enqueue. This is confirmed when I changed it to `UserMailer.first_email(id).deliver_later` and the error is correctly thrown at `send_first_email`

2. I'm not sure if I understand the second problem, my expectation is error shouldn't be thrown because `send_second_email` it's done after the transaction in `after_commit`. Is this correct?

I'm using `ruby 2.6.5` and `rails 5.1.7`

**Comment by palkan** [comment]
> I believe the first problem is the mailer adapter doesn't recognize

What is `delay`? Sidekiq delay extensions or delayed_job? If you use delayed_job then it shouldn't raise, since delaying the execution means storing the record in the DB, and thus it only "survives" if the transaction commits.

> my expectation is error shouldn't be thrown because send_second_email it's done after the transaction in after_commit

Correct. The bug is probably with the transaction detection in test env. Have you tried to run the create code in dev mode (i.e., in `rails c`)? Do you use `transactional_tests` or DatabaseCleaner?

**Comment by mquan** [comment]
> What is `delay`?

It's [sidekiq delay extensions](https://github.com/mperham/sidekiq/wiki/Delayed-extensions)

> Have you tried to run the create code in dev mode (i.e., in rails c)?

Yes, things are working as expected in dev (aside from `delay` problem above)

> Do you use transactional_tests or DatabaseCleaner?

DatabaseCleaner. I dug a little deeper and found that before the actual test portion, `Isolator.transactions_threshold` is 2 and `Thread.current.fetch(:isolator_transactions, 0)` is also 2. So it makes sense that `send_second_email` triggers an error. I believe this is a problem on my side, there's one more layer of transaction wrapped in my test setup somewhere.

**Comment by palkan** [comment]
> Isolator.transactions_threshold is 2

Could you share your DatabaseCleaner configuration?

Which Rails version do you use, btw?

> It's sidekiq delay extensions

We probably need some tests for this case first)

**Comment by mquan** [comment]
> Could you share your DatabaseCleaner configuration?

```ruby
RSpec.configure do |config|
  config.around do |example|
    # this is for ar_after_transaction: https://github.com/grosser/ar_after_transaction#transactional-fixtures---normally_open_transactions
    ActiveRecord::Base.normally_open_transactions = 0

    example.run
    DatabaseCleaner.clean_with(:truncation, pre_count: true)
  end
end
```

> Which Rails version do you use, btw?
5.1.7 (ruby 2.6.5)

**Comment by palkan** [comment]
Could you try disabling `ar_after_transaction`? They do some [AR monkey-patching](https://github.com/grosser/ar_after_transaction/blob/f3a24ccf7df650519a694e8f2aaa52a0a1e5d6dc/lib/ar_after_transaction.rb#L9-L10), probably, incompatible with Isolator.

P.S. Btw, there is a better alternative to this gem which uses AR API with zero monkey-patching: https://github.com/Envek/after_commit_everywhere.

**Comment by mquan** [comment]
> Could you try disabling ar_after_transaction?

Disabling it didn't help. But I workaround it by adding 1 more to `Isolator.transactions_threshold` in test environment. It's not a permanent solution but at least it allows me to run tests and identify the true violations.

Any word on supporting sidekiq delay extensions (the first problem)?

**Comment by palkan** [comment]
> Any word on supporting sidekiq delay extensions (the first problem)?

Couldn't reproduce (see [the test](https://github.com/palkan/isolator/commit/3f03f3f26c6be2a7c0e7302a122798c4af98320b)). 
Could you please try to write a single file reproduction script (e.g., using a Rails [bug report template](https://github.com/rails/rails/blob/master/guides/bug_report_templates/active_record_gem.rb))?

**Comment by palkan** [comment]
Which version of DatabaseCleaner do you use? Is it 1.8.0+ (it has a lot of internal [changes](https://github.com/DatabaseCleaner/database_cleaner/blob/master/History.rdoc#180-2020-01-29-))?

**Comment by mquan** [comment]
I figured out the mystery with sidekiq delay extension problem. We have an override that defers `delay` call to after transaction, so it makes sense that isolator doesn't throw error when enqueuing jobs with `.delay`

**Comment by mquan** [comment]
thanks a lot for your quick responses, I'm closing the ticket since both problems originated from my side
