### ISSUE TITLE
Using isolator with multiple database connections

### ISSUE THREAD

**Issue by mquan** [palkan/isolator#28]
In our app, we're using multiple db connections, and some of them establish connection lazily.  In one instance, we notice that simply connecting to a new db increments `Thread.current[:isolator_transactions]`. I'm guessing a new connection matches the `START_PATTERN` https://github.com/palkan/isolator/blob/234b6f69f1c8d8b0fabfc8afb91e8cb67dfd7229/lib/isolator/orm_adapters/active_support_subscriber.rb#L7. Do you have a recommended way for dealing with multiple connections?

**Comment by palkan** [comment]
> Do you have a recommended way for dealing with multiple connections?

Unfortunately, no. Isolator was designed for single connection per thread usage, and it's not that simple to make it work with multiple connections.

What you can do is to patch the subscriber and make it ignore queries from non-primary connection. Smth like this:

```ruby
def self.subscribe!(event)
  ::ActiveSupport::Notifications.subscribe(event) do |_name, _start, _finish, _id, query|
    # not sure about this one
    next unless query[:connection] == ActiveRecord::Base.connection

    Isolator.incr_transactions! if START_PATTERN.match?(query[:sql])
    Isolator.decr_transactions! if FINISH_PATTERN.match?(query[:sql])
  end
end
```

We should track connections separately using their ids. That would require some work.

Could you please provide a reproduction example or, much better, open a PR to Isolator with a test scenario for multiple connections? That would help us to fix this quicker.

**Comment by mquan** [comment]
> What you can do is to patch the subscriber and make it ignore queries from non-primary connection.

Do you think we still want to catch violations inside non-primary db transaction?

> We should track connections separately using their ids.

It sounds like this statement means we track `isolator_transactions` per connection? This makes sense to me. Although I think the remaining challenge is to identify and ignore sql of connection establishment. May be we can use it as the trigger for initializing a new `isolator_transactions`.
Do you think using the db_config's host, adapter, and database would be a good connection identifier?

As for repro example

```ruby
class Foo < ActiveRecord::Base
  self.establish_connection db_config
end

# simply reference the class would increment the count
# Assume users table is the main connection being tracked by isolator
# Thread.current[:isolator_transactions] == 0
User.transaction do
  # Thread.current[:isolator_transactions] == 1
  Foo
  Thread.current[:isolator_transactions] == 2
end
Thread.current[:isolator_transactions] == 1
```

I haven't tried but base on your comment may be the following is enough to throw off the count
```ruby
User.transaction do
  ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
end
```

**Comment by palkan** [comment]
Hey @mquan!

Finally, I found some time to invest into this feature. I took your PR and added some changes: https://github.com/palkan/isolator/pull/32

It would be great if you try this branch in your project (we're currently testing it internally, too).

**Comment by mquan** [comment]
@palkan awesome, I tested it out in our repo, and it fixes the problem. I also added a few offenses in both main and secondary dbs and it correctly identifies them. Great job 👍
