### ISSUE TITLE
Being able to allow/ignore inside a specific transaction

### ISSUE THREAD

**Issue by Mange** [palkan/isolator#34]
Sometimes you actually *do* want to allow actions to happen inside a transaction, for example a plain lock.
The failure case could be that you rather repeat the action than perhaps missing to run the action, so you wrap it inside a lock.

```ruby
reminder.with_lock do
  Something.deliver_reminder(reminder)
  reminder.update!(sent: true)
end
```

This will cause a problem with Isolator, with no apparent way to protect from it.

It would be great with any one of these:

```ruby
reminder.with_lock do
  Isolator.allow do
    Something.deliver_reminder(reminder)
  end
  reminder.update!(sent: true)
end
```

or if that's not feasible: 

```ruby
Isolator.adapter.something.ignore_if { |args, object, method|
  object.instance_of?(Something) && method == :deliver_reminder
}
# …
reminder.with_lock do
  Something.instance.deliver_reminder(reminder)
  reminder.update!(sent: true)
end
```

I've read the source code trying to find a good way to do this. I could try to hook into the current "TODO" system, but that is not optimal because:

1. It implies that it's a problem that should be solved some day ("TODO")
2. It's based on filenames and/or line numbers, and not context.

The current `ignore_if` only passes along the arguments, which means it's not possible to see *which* `ActiveJob` is being looked at. (`SomeJob.perform_later` would have `args == []`)

Writing my own `Ignorer` class seems excessive, and it lacks examples on how to do it. I find the interface I'm supposed to implement to be a bit hard to see.

I could call `disable!` and `enable!` on the adapter, but that is not thread-safe.

My proposed solutions have one glaring problem, which is: What if you only load Isolator in development/test? Then `Isolator.allow` will be undefined.
I would solve this by actually wrapping it in my own helpers, so that would not be a problem for me, but it would have to be documented.

```ruby
private

def allow_inside_transaction
  if defined?(Isolator)
    Isolator.allow { yield }
  else
    yield
  end
end
```

**Comment by Mange** [comment]
For now I'll implement this using my own little thread variable.

```ruby
class IsolatorAllower
  def self.allow
    Thread.current[:isolator_ignore] = true
    yield
  ensure
    Thread.current[:isolator_ignore] = nil
  end
end

if defined?(Isolator)
  Isolator.adapter.something.ignore_if { Thread.current[:isolator_ignore] }
  Isolator.adapter.something_else.ignore_if { Thread.current[:isolator_ignore] }
end
```

I have not tested this yet, but I think it'll work.

**Comment by palkan** [comment]
> I could call disable! and enable! on the adapter, but that is not thread-safe.

Hm, it is, we use `Thread.current`:  https://github.com/palkan/isolator/blob/395186eaa299411c5db5396bc7cfba5e1d3f7c87/lib/isolator.rb#L20-L34

And you can pass a block: `Isolator.disable { do_stuff }`.

> have one glaring problem, which is: What if you only load Isolator in development/test? 

Exactly. Isolator is designed to be used in dev/test/staging/whatever-but-production environment.

So, something like `allow_inside_transaction` should be defined outside of the gem.

Or, maybe:

```rb
# config/initializers/isolator.rb
return if defined?(Isolator)

module Isolator
  def self.disable
    yield
  end
end
```

**Comment by Mange** [comment]
That is embarrassing on my part. I apologize. It sure is right there for me to look at!

I must've completely missed the `disable` method and only saw the `disable!` one. I came out of a very frustrating troubleshooting session, so I must've been in complete tilt mode by then.

Thankfully my mistake serves as searchable keywords for others in the same mental state in the future! :laughing:
