### ISSUE TITLE
Isolator behaves differently between rails 6.1.3.2 and 6.1.4

### ISSUE THREAD

**Issue by mquan** [palkan/isolator#35]
We recently upgraded from rails 6.1.3.2 to 6.1.4 and found that when there's a `ActiveRecord::Deadlocked` exception, isolator does not clean up the stale connection properly. This may be due to rails changing how it handles deadlock. It seems rails 6.1.4 disconnects the db connection and establishes a new one.

In rails 6.1.3.2: when `ActiveRecord::Deadlocked` is raised, `ActiveRecord::Base.connected?` does not change and the same connection id is seen in `Isolator.state[:transactions]`.

In rails 6.1.4 when `ActiveRecord::Deadlocked` is raised, `ActiveRecord::Base.connected?` changes from true to false. Inspecting `Isolator.state[:transactions]` subsequently will show both the dead and new connection ids. If `ActiveRecord::Deadlocked` is raised within a transaction, then the dead connection's transactions count remains higher and will fail `within_transaction?` check.

Do you think isolator should listen to disconnect event and remove the dead connection from `Isolator.state[:transactions]`?

**Comment by palkan** [comment]
> Do you think isolator should listen to disconnect event and remove the dead connection from Isolator.state[:transactions]?

Yeah, that makes sense. And I think, that's the only way to deal with this situation.

Would you like to provide a fix?

**Comment by mquan** [comment]
I'd love to help. I haven't looked too deeply, do you know if there's a hook or pattern that we can latch onto to detect disconnection?

**Comment by mquan** [comment]
@palkan here's my attempt at a fix https://github.com/palkan/isolator/pull/36. The callback doesn't seem to get invoked on disconnection. LMK if you notice anything obviously wrong, otherwise, I'll keep digging.
