### ISSUE TITLE
Mailer is not present in Isolator.adapters after initialize

### ISSUE THREAD

**Issue by bohdan-perekhrest-rg** [palkan/isolator#56]
## What did you do?
Installed gem
add .isolator_ignore.yml where add
`
  mailer:
    - app/concepts/api/v1/lib/operation/bookings/create_transaction.rb
`

## What did you expect to happen?
my tests are passed

## What actually happened?
got 
`
Isolator::MailerError
...
...
`

## Additional context
  Failures:
  
    1) Api::V1::Workspaces::Bookings::Operation::Update Success updates booking
       Failure/Error: notify(*args, **kwargs, sync: true)
       
       Isolator::MailerError:
         You are trying to send email inside db transaction.
         Details: From: ["notifications@example.io"]
         To: ["rodrick.cronin@parker.co.uk"]
         Subject: New Payment from Rosalee Feest is due Feb 22, 2023

## Environment

**Ruby Version: 3.1.2**

**Framework Version (Rails, whatever): rails 7.0.4**

**Isolator Version: 0.8.0**

**Comment by palkan** [comment]
Thanks for the report (and sorry for the late reply).

We reload adapters right before setting up the ignore configuration: https://github.com/palkan/isolator/blob/f5581e048d5469e72b044faca4e0087cdc2f8c4b/lib/isolator/railtie.rb#L16

I think, Rails no longer loads the `ActionMailer::Base` during initialization, so we only activate the adapter as soon as you load a mailer class.

I have a quick fix in mind, will push soon.
