### ISSUE TITLE
Isolator raises exceptions when using DatabaseCleaner with multiple DBs 

### ISSUE THREAD

**Issue by emijero** [palkan/isolator#61]
## What did you do?

We recently setup DatabaseCleaner to work with multiple DBs and Isolator is raising errors on tests in which we persist models
with `after_commit` callbacks that enqueue background jobs. I also checked with HTTP requests made in after `after_commit` callbacks and it also raises exceptions.

Happy to submit a PR for the fix. Thank you!

## What did you expect to happen?

It should not raise errors for jobs enqueued or HTTP request performed on `after_commit` callbacks.

## Additional context

To reproduce it:
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'activejob', '~> 7.0.5.1'
  gem 'activerecord', '~> 7.0.5.1'
  gem 'sqlite3'
  gem 'rspec'

  gem 'database_cleaner'
  gem 'isolator', '~> 0.9.0', require: false
end

require 'active_job'
require 'active_record'
require 'rspec/autorun'

require 'uri'
require 'net/http'

PRIMARY_DB   = 'primary.sqlite3'
SECONDARY_DB = 'secondary.sqlite3'

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: PRIMARY_DB)
ActiveRecord::Schema.define do
  create_table :animals do |t|
    t.string :name, null: false
  end
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: SECONDARY_DB)
ActiveRecord::Schema.define do
  create_table :pets do |t|
    t.string :nickname, null: false
  end
end

class DummyJob < ActiveJob::Base; end

class Animal < ActiveRecord::Base
  self.establish_connection(adapter: 'sqlite3', database: PRIMARY_DB)

  after_commit { DummyJob.perform_later }
end

class Pet < ActiveRecord::Base
  self.establish_connection(adapter: 'sqlite3', database: SECONDARY_DB)

  after_commit { Net::HTTP.get_response(URI('https://www.google.com/')) }
end

RSpec.configure do |config|
  DatabaseCleaner[:active_record, db: Pet].strategy    = :transaction
  DatabaseCleaner[:active_record, db: Animal].strategy = :transaction

  config.before(:each) { DatabaseCleaner.start }

  config.after(:each) { DatabaseCleaner.clean }

  require 'isolator'

  Isolator.configure { |isolator_config| isolator_config.raise_exceptions = true }
end

RSpec.describe 'Errors' do
  it { Pet.create(nickname: 'Spike') }
  it { Animal.create(name: 'Dog') }
end
```

It seems to always increment the transactions threshold for the same connection. In `lib/isolator/database_cleaner_support.rb` we could assign a lambda that leverages the `connection_class` used by [DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner-active_record/blob/1b4b4785da41ee910baed193da5d9d5f06a8ddbc/lib/database_cleaner/active_record/base.rb#L39) before increasing/decreasing the transactions threshold on the `start` and `clean` methods:

```ruby
Isolator.default_connection_id = -> { connection_class.connection.object_id }
```
 
Thoughts?

## Environment

**Ruby Version:** `3.2.1`

**Framework Version (Rails, whatever):**  ActiveRecord `7.0.5.1` and ActiveJob `7.0.5.1`

**Isolator Version:** `0.9.0`

**Comment by palkan** [comment]
Thanks a lot for the reproduction. Fixed and released in 0.10.0.
