### ISSUE TITLE
Corrupt transaction counts when connection closes unexpectedly

### ISSUE THREAD

**Issue by composerinteralia** [palkan/isolator#64]
## What did you do?

I doubt this is a bug in practice, since connections don't tend to go away all of a sudden in test (maybe in staging if the gem is used there?). But I figured I'd report it anyway, at least as further discouragement from using this in production environments.

I wrote a test to demonstrate the problem. If the database connection closes before the transaction completes, we can fail to either commit or rollback, leaving the transaction count permanently incremented.

```rb
    context "when the connection fails" do
      specify do
        expect(Isolator).to_not be_within_transaction

        begin
          ar_class.transaction do
            ar_class.all.to_a
            expect(Isolator).to be_within_transaction

            # Imitate a problem with the underlying connection, preventing us from committing or rolling back
            allow(ar_class.connection).to receive(:commit_db_transaction).and_raise("Failed to commit")
            allow(ar_class.connection).to receive(:rollback_db_transaction).and_raise("Failed to rollback")
          end
        rescue
        end

        # The counts are off now, so this fails
        expect(Isolator).to_not be_within_transaction
      end
    end

```

We've got some transaction tracking stuff at GitHub that patches the Rails `TransactionManager`, and we've got an `ensure` there that allows us to decrement counters even if we fail to commit or rollback. There's perhaps an argument to be made for adding some transaction-specific instrumentation to Rails itself that we could use instead.

## What did you expect to happen?

Ideally this test would pass, but I understand why it doesn't. There's nothing coming through `sql.active_record` that would indicate a failed rollback.

## What actually happened?

It fails

## Environment

**Ruby Version:**

**Framework Version (Rails, whatever):**

**Isolator Version:**

**Comment by palkan** [comment]
Thanks for the report!

> There's nothing coming through sql.active_record that would indicate a failed rollback.

Yeah, and this event is our only source of truth.

> There's perhaps an argument to be made for adding some transaction-specific instrumentation to Rails itself that we could use instead.

From a quick look, I see that there is a [checkin callback](https://github.com/rails/rails/blob/735cba5bed7a54c7397dfeec1bed16033ae286f8/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L17) we can probably use to handle connection closure. Not sure if it's robust enough though.

> But I figured I'd report it anyway, at least as further discouragement from using this in production environments.

I'm surprised closing a connection with an open transaction does not result in a "ROLLBACK" query being issued—that's what happened, right?

**Comment by composerinteralia** [comment]
> I'm surprised closing a connection with an open transaction does not result in a "ROLLBACK" query being issued—that's what happened, right?

In the case I'm describing, the connection gets closed by the server without the adapter's knowledge (a real thing that happens to us daily at GitHub), so there would be no chance to issue a ROLLBACK.

```rb
ar_class.transaction do
  ar_class.all.to_a
  # MySQL server terminates the connection, or there's some network error that
  # causes it to go away without the adapter's knowledge. Rails attempts a "COMMIT"
  # or "ROLLBACK" but either fails because there is no open connection
end
```

**Comment by composerinteralia** [comment]
https://github.com/rails/rails/pull/49192 was merged, so that might be a more reliable option for the future

**Comment by palkan** [comment]
Wow! That's awesome! I was discussing the idea of adding a custom `isolator.transaction` event as a wrapper over `sql.active_record`. So, I think the plan would be to implement it for Rails <7.1 as a kinda backport and use `transaction.active_record` if available.
