### ISSUE TITLE
Incompatible character encodings when logging jobs with non-utf8 arguments

### ISSUE THREAD

**Issue by composerinteralia** [palkan/isolator#66]
## What did you do?

Tried running isolator against the GitHub test suite and saw a number of `incompatible character encodings: ASCII-8BIT and UTF-8` errors.

Here's a test to reproduce the problem:

```rb
  context "when logging non-utf8 details" do
    specify do
      logger = instance_double("Logger")
      Isolator.configure do |config|
        config.logger = logger
      end

      job_args = ["abc123", "\xff".dup.force_encoding(Encoding::ASCII_8BIT)]
      details = "MyJob (#{job_args.join(", ")})"
      exception = Isolator::BackgroundJobError.new(details: details)

      described_class.new(exception).call
    end
  end
```

Because of the ASCII_8BIT job argument, the whole exception message ends up as ASCII_8BIT. We're able to combine that just fine with other ascii-only strings, but we're not able to combine that with [the UTF_8 `↳` used to print the backtrace](https://github.com/palkan/isolator/blob/3c925c8fbf037c889a34e3e8bc8dfce6874233a8/lib/isolator/notifier.rb#L36).

## What did you expect to happen?

I'm not certain. Encodings can be difficult...

A fallback to leave out the `↳` if there's any sort of encoding problem, perhaps? Or replace it with `-` or something else ascii that's likely to be more broadly compatible?

## Environment

**Ruby Version:**

3.2

**Framework Version (Rails, whatever):**

Rails main (7.1)

**Isolator Version:**

0.10.0

**Comment by palkan** [comment]
Thanks! Fixed (decided to go with retry+fallback for now).
