### ISSUE TITLE
Inline isolator exceptions

### ISSUE THREAD

**Issue by alexevanczuk** [palkan/isolator#72]
## Is your feature request related to a problem? Please describe.

When we change code, `.isolator_ignore.yml` needs to be updated with new line numbers.

There are valid reasons to have ignored things, for example if a failed call to an external service should roll back the transaction

## Describe the solution you'd like

It would be great if we could do what rubocop does, e.g .`my_exception # rubocop:disable Some/Rule`.

I think directly above the line makes the most sense, e.g. `# isolator:disable MyException`

## Describe alternatives you've considered

I looked into whether the current API for the dependency injected ignore class could support this. I thought maybe I could check the frame where the exception happened and check for the comment above the line number of the frame where the exception was raised? I could potentially do this with no code in the gem, but it would be great if this was a first-class feature.

## Additional context

n/a

**Comment by alexevanczuk** [comment]
If it helps:
`prism` (which is the new Ruby AST parser that shopify is migrating their system to use) just released an API to extract comments only from a file, which might work as an implementation idea:

https://github.com/ruby/prism/releases/tag/v0.16.0

**Comment by alexevanczuk** [comment]
I found a simpler solution:

In `config/initializers/isolator.rb`:
```ruby
# typed: strict
# frozen_string_literal: true

require 'my_isolator'

Isolator.configure do |config|
  config.ignorer = MyIsolator::Ignorer
end

```

In `lib/my_isolator.rb`:
```ruby
# By default, the isolator gem uses an `.isolator_ignore.yml` file to ignore exceptions.
# Here's an example file:
#
# mailer:
#   - path/to/myfile1:128
#   - path/to/myfile2:277
#
# This approach is a bit annoying because whenever you change the file, the line numbers need updating.
# You also need to run `spring stop` after updating the file since it's cached by spring.
#
# Isolator allows you to override the ignorer:
# https://github.com/palkan/isolator#configuration
#
# The new approach uses a no-op method to wrap things to ignore in a block.
# Example:
#
# MyIsolator.ignore_non_transactional_writes do
#   MyMailer.new.some_email(...).deliver
# end
#
module MyIsolator
  extend T::Sig
  extend T::Helpers
  sig do
    type_parameters(:U).params(block: T.proc.returns(T.type_parameter(:U))).returns(T.type_parameter(:U))
  end
  def self.ignore_non_transactional_writes(&block)
    block.call
  end

  class Ignorer
    extend T::Sig

    # This uses the same API and approach (checking a backtrace) as the gem does here:
    # https://github.com/palkan/isolator/blob/master/lib/isolator/ignorer.rb#L48
    sig { params(path: T.nilable(String), regex_string: T.nilable(String)).void }
    def self.prepare(path:, regex_string: T.unsafe(nil)) # rubocop:disable Lint/UnusedMethodArgument
      Isolator.adapters.each do |_id, adapter|
        adapter.ignore_if do
          caller.any? do |line|
            line.include?('ignore_non_transactional_writes')
          end
        end
      end
    end
  end
end

```

**Comment by palkan** [comment]
Hey!

Thanks for the suggestion and the proposed solution. 

I would probably optimize the check a bit as follows (or smth like that):

```ruby
IGNORER_LOCATION = [__FILE__, __LINE__ + 2].freeze
def self.ignore_non_transactional_writes(&block)
   block.call
end

# ...

adapter.ignore_if do
  # Use Thread::Backtrace::Location objects https://rubyapi.org/3.2/o/thread/backtrace/location
  caller_locations.any? do |loc|
    loc.path == IGNORER_LOCATION.first && loc.lineno == IGNORER_LOCATION.last
  end
end
``` 

`caller` + `include?` may become noticeably slow.

----

As for inline comments, I think, we can actually use the to update the `.isolator_ignore.yml` file; that would require calling smth like `rake isolator:todo:sync`, but it's much better than syncing manually.
