### ISSUE TITLE
Rails 7.1 compatibility

### ISSUE THREAD

**Issue by sunny** [palkan/isolator#74]
## What did you do?

Tried to upgrade an app from Rails 7.0.8 to Rails 7.1 with the following initializer:

```rb
# frozen_string_literal: true

if defined?(Isolator)
  # Check can be disabled since we have transactional_push enabled in Sidekiq.
  Isolator.adapters.active_job.disable!
end
```

## What actually happened?

The following exception is raised on boot:

```
/Users/sunny/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/isolator-1.0.1/lib/isolator/simple_hashie.rb:12:in `block in method_missing': undefined method `active_job' for {"http"=>#<Module:0x000000010cdeb1d0>, "sidekiq"=>#<Module:0x000000010cde1270>, "mailer"=>#<Module:0x000000010cdd9c28>}:Isolator::SimpleHashie (NoMethodError)
	from /Users/sunny/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/isolator-1.0.1/lib/isolator/simple_hashie.rb:12:in `fetch'
	from /Users/sunny/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/isolator-1.0.1/lib/isolator/simple_hashie.rb:12:in `method_missing'
	from /Users/sunny/code/cults/config/initializers/isolator.rb:5:in `<main>'
```

## Additional content

Commenting out the disabling boots the app with no issue.

## Environment

**Ruby Version:** 3.1.3

**Framework Version:** Rails 7.1.2 (previously 7.0.8)

**Isolator Version:** 1.0.1

**Comment by palkan** [comment]
Looks like something has changed in the way Rails loads Active Job. We rely on the load hooks to activate the adapter: https://github.com/palkan/isolator/blob/cce27e2353fb3f21adbfc0f1f36e355c96e9ccf6/lib/isolator/adapters/background_jobs.rb#L4

And we can't see in the error message that it hasn't been triggered during the application boot.

A quick fix could be adding `require "active_job/base"` right before the Isolator call. However, it would be great to figure out what caused the hook execution in Rails <7.1 🤔

**Comment by sunny** [comment]
Hi @palkan! Thank you, I can confirm that `require "active_job/base"` in my initializer does the trick 👍🏻
